### PR TITLE
vnext - Update to use ArcGIS runtime update 10

### PR DESCRIPTION
**Pull request by puneet-pdx**
- Update versions - 
   Android Gradle Plugin Version - 4.1.2
   Gradle version - 6.5
   Min SDK - 23 required by ArcGIS runtime
   ArcGIS runtime version - 100.10.0
   test runner version
   materialLibraryVersion
   appcompatLibraryVersion

- Update app versionName to 0.1.4

### CODE REVIEW

**Review by gunt0001 — APPROVED** [review]

**Review by changanxian — APPROVED** [review]
👍

**Comment by puneet-pdx** [comment]
@esreli can you please review.

**Comment by esreli** [comment]
Instead of issuing two PRs, could you use the changes made to [main](https://github.com/Esri/data-collection-android/pull/14) and merge (or rebase) them onto `v.next`? This way, we don't have to have two concurrent PRs.

**Comment by puneet-pdx** [comment]
@esreli merge(or rebase) is giving me conflicts as v.next and master are in different states. I have made the same change in this PR.

**Review by esreli — COMMENTED** [review]
LGTM

**Pull request merged**
